import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '1.18.0:0',
  releaseNotes: {
    en_US:
      "Updates Hashrate Autopilot to upstream 1.18.0. You can now declare which Ocean chain you mine on, under Config → Pool & Payout. Mainstream is the default and behaves exactly as before. If you point your miners at Ocean's BIP110 endpoint, choose BIP110: Ocean publishes no API for that chain, so instead of reporting zeros the dashboard says plainly what it cannot show, derives collected Profit & Loss from the on-chain payouts your own Bitcoin node sees, and disables the hashprice-based price cap and cheap mode, since no hashprice exists there — your fixed Maximum bid becomes the only ceiling. Bidding continues on either chain. Switching takes effect within a minute and needs no restart, and database migrations run automatically on first start.",
    es_ES:
      'Actualiza Hashrate Autopilot a la versión 1.18.0. Ahora puedes indicar en qué cadena de Ocean minas, en Configuración → Pool y pagos. Mainstream es la opción predeterminada y se comporta igual que antes. Si diriges tus mineros al endpoint BIP110 de Ocean, elige BIP110: Ocean no publica ninguna API para esa cadena, así que en lugar de mostrar ceros el panel indica con claridad lo que no puede mostrar, obtiene las ganancias cobradas a partir de los pagos en cadena que ve tu propio nodo de Bitcoin, y desactiva el límite de precio basado en el hashprice y el modo económico, porque allí no existe hashprice: tu puja máxima fija pasa a ser el único techo. La puja continúa en ambas cadenas. El cambio surte efecto en menos de un minuto y no requiere reiniciar, y las migraciones de la base de datos se ejecutan automáticamente al primer arranque.',
    de_DE:
      'Aktualisiert Hashrate Autopilot auf Upstream 1.18.0. Sie können jetzt unter Konfiguration → Pool und Auszahlung angeben, auf welcher Ocean-Chain Sie mining betreiben. Mainstream ist die Voreinstellung und verhält sich unverändert. Wenn Sie Ihre Miner auf Oceans BIP110-Endpunkt richten, wählen Sie BIP110: Ocean veröffentlicht für diese Chain keine API, daher zeigt das Dashboard statt Nullwerten klar an, was es nicht darstellen kann, leitet die vereinnahmten Gewinne aus den On-Chain-Auszahlungen ab, die Ihr eigener Bitcoin-Knoten sieht, und deaktiviert die hashpreisbasierte Preisobergrenze sowie den Sparmodus, da es dort keinen Hashpreis gibt — Ihr fest eingestelltes Maximalgebot ist dann die einzige Obergrenze. Das Bieten läuft auf beiden Chains weiter. Ein Wechsel wirkt innerhalb einer Minute und erfordert keinen Neustart; Datenbank-Migrationen laufen beim ersten Start automatisch.',
    pl_PL:
      'Aktualizuje Hashrate Autopilot do wersji 1.18.0. Możesz teraz wskazać, na którym łańcuchu Ocean kopiesz, w Konfiguracja → Pool i wypłaty. Mainstream jest ustawieniem domyślnym i działa tak jak dotychczas. Jeśli kierujesz koparki na endpoint BIP110 Ocean, wybierz BIP110: Ocean nie udostępnia API dla tego łańcucha, więc zamiast pokazywać zera panel wprost informuje, czego nie może przedstawić, wylicza zainkasowane zyski z płatności on-chain widzianych przez Twój własny węzeł Bitcoin i wyłącza limit ceny oparty na hashprice oraz tryb oszczędny, ponieważ hashprice tam nie istnieje — jedynym pułapem pozostaje Twoja stała oferta maksymalna. Licytacja działa dalej na obu łańcuchach. Zmiana zaczyna obowiązywać w ciągu minuty i nie wymaga restartu, a migracje bazy danych wykonują się automatycznie przy pierwszym uruchomieniu.',
    fr_FR:
      "Met Hashrate Autopilot à jour vers la version 1.18.0. Vous pouvez désormais indiquer sur quelle chaîne Ocean vous minez, dans Configuration → Pool et paiements. Mainstream est la valeur par défaut et se comporte comme avant. Si vous dirigez vos mineurs vers le point d'accès BIP110 d'Ocean, choisissez BIP110 : Ocean ne publie aucune API pour cette chaîne, donc au lieu d'afficher des zéros le tableau de bord indique clairement ce qu'il ne peut pas montrer, déduit les gains encaissés des paiements on-chain que voit votre propre nœud Bitcoin, et désactive le plafond de prix fondé sur le hashprice ainsi que le mode économique, puisqu'aucun hashprice n'existe là-bas : votre enchère maximale fixe devient le seul plafond. Les enchères se poursuivent sur les deux chaînes. Le changement prend effet en moins d'une minute et ne nécessite aucun redémarrage, et les migrations de base de données s'exécutent automatiquement au premier démarrage.",
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
